"""Per-repository template for tools/build_notebook.py (NOTEBOOK_SPEC 2.2 §4 standalone carrier).

Only the task-specific prose and stage cells live here. Runtime install, the embedded pipeline
modules (modeling.py, metrics.py, pipeline.py, samples.py), and the model pin/stage/verify cells are produced
by the generator from repository sources so they cannot drift from the package.

This template configures an E2E change-detection workflow: the pinned CFNet LEVIR-CD checkpoint (a torch pickle
of the state dict) is digest-verified, statically audited and converted once into safetensors, 64 labelled
bi-temporal crops are extracted from the digest-pinned LEVIR-CD tarball, validated and assigned the dataset's own
splits, the frozen model is scored against the all-unchanged baseline, a bounded fine-tuning of the change decoder
runs, the held-out pairs are scored again, change maps are written, and the adapter is exported and reloaded.

Review fixes (Notebook Review Framework v1, review PR #7, CFN-M1..M5 / CFN-m1..m5): the runtime is the fleet's uv
isolated environment (no in-kernel install, no restart); epoch selection uses a deterministic validation loss and
the notebook shows its draw-to-draw noise; every pass of Sections 5-6 starts from the pretrained model; BYOD gets a
real minimum, source ids, member resolution and archive ceilings; and the guided layer (audience, how to use,
roadmap, predictions, worked answers, a change-one-thing activity, troubleshooting, glossary, conclusion) is added.
"""
# ruff: noqa: E501  -- markdown prose and code-cell text are kept on single lines for readable rendering

REPO = "cfnet-change-detection-pipeline"

BADGES = [
    (
        "GitHub",
        "https://img.shields.io/badge/GitHub-181717?style=flat&logo=github&logoColor=white",
        f"https://github.com/kurtvalcorza/{REPO}",
    ),
    (
        "Open In Colab",
        "https://colab.research.google.com/assets/colab-badge.svg",
        f"https://colab.research.google.com/github/kurtvalcorza/{REPO}/blob/main/tutorials/cfnet_change_detection_colab.ipynb",
    ),
    (
        "Hugging Face",
        "https://img.shields.io/badge/%F0%9F%A4%97%20Hugging%20Face-wifibk%2FCFNet-ffcc4d?style=flat",
        "https://huggingface.co/wifibk/CFNet",
    ),
    (
        "Upstream",
        "https://img.shields.io/badge/Upstream-wifiBlack%2FCFNet-181717?style=flat&logo=github&logoColor=white",
        "https://github.com/wifiBlack/CFNet",
    ),
    ("Paper", "https://img.shields.io/badge/arXiv-2503.08505-b31b1b.svg", "https://arxiv.org/abs/2503.08505"),
]

TEMPLATE = {
    "package": "cfnet_change_detection_pipeline",
    "repo_name": REPO,
    "stem": "cfnet_change_detection",
    "notebook_name": "cfnet_change_detection_colab.ipynb",
    "profile": "E2E",
    "mode": "GUIDED",
    "infrastructure_labels": True,
    "isolated_runtime": True,
    # The fleet's uv isolated-environment mechanism (bart-mnli-zero-shot-classification-pipeline ee128d2 /
    # bert-masked-lm-pipeline 7b73463, generator /2.1): managed CPython, a size- and SHA-256-verified uv wheel, and a lock
    # compiled from the pyproject pins with `uv pip compile pyproject.toml --python-version 3.12 --python-platform
    # x86_64-manylinux_2_28 --generate-hashes --only-binary :all: -o tutorials/requirements-colab.lock.txt`, shared
    # transitive versions constrained to depth-anything-depth-estimation-pipeline's lock (same torch / torchvision pins).
    "managed_python": "3.12.12",
    "uv": {
        "version": "0.12.15",
        "url": "https://files.pythonhosted.org/packages/1e/fd/432451d732917c49152a291de3ef171aa6b0f1a22d39780fb2c1f085ca4c/uv-0.12.15-py3-none-manylinux_2_17_x86_64.manylinux2014_x86_64.whl",
        "bytes": 20081404,
        "sha256": "aee9802f46bae436bd91751bb33ddeb379ef1596b5c19df193219d545d244b60",
    },
    "lock": "tutorials/requirements-colab.lock.txt",
    "external_access_extra": (
        "the 3.8 GB (3,831,872,824 bytes) `LEVIR-CD-processed.tar.gz` of the Hugging Face dataset `wifibk/CFNet_Datasets` "
        "(the CFNet authors' mirror) at an immutable revision, digest-verified before any member is read"
    ),
    "run_all": (
        "Selecting **Run all** in a fresh runtime (Linux x86_64: Google Colab, Kaggle or Linux Jupyter; GPU recommended, CPU "
        "works) builds an isolated Python environment from a hash-locked requirements file (torch, torchvision, numpy, pillow, "
        "safetensors, huggingface-hub — the network is carried in this notebook, the EfficientNet-B5 stages come from the "
        "installed torchvision with no download) without touching the kernel's own packages, so no restart is ever needed; "
        "stages and digest-verifies the pinned CFNet LEVIR-CD checkpoint (15.8 MB) from the Hub, statically audits the pickle "
        "against an allow-list, converts it once into safetensors with a pinned digest, rebuilds the network from the carried "
        "module and loads it strictly; fetches the digest-pinned LEVIR-CD tarball (3.8 GB, no credential) and extracts exactly "
        "the 192 pinned before / after / label members; validates them and assigns the dataset's own splits (32 training, 8 "
        "validation, 24 test crops); detects change on the held-out pairs with the frozen model and scores them against the "
        "all-unchanged baseline; runs a bounded fine-tuning of the change decoder in which the frozen model competes as epoch "
        "0; scores the same pairs again; writes change maps for two held-out pairs beside their images and labels; exports the "
        "adapter as safetensors with a manifest; and reloads that artifact into a fresh pipeline to verify prediction parity. "
        "The default path needs no repository clone, no DIMER worker or service, no credential, no upload dialog and no "
        "configuration edit (NOTEBOOK_SPEC 2.2 §5)."
    ),
    "byod": (
        "After the tutorial workflow completes, set `USE_BYOD = True` in Section 4 (and, outside Colab, `BYOD_PATH`), select "
        "that cell and choose **Runtime → Run after** to supply your own labelled pairs: a zip (or a directory) holding "
        "`pairs.csv` (columns `id`, `before`, `after`, `label`; file paths relative to `pairs.csv`) beside co-registered RGB "
        "PNG / JPEG images of the same size (sides multiples of 32) and single-band label PNGs (0 = unchanged, 255 = changed); "
        "at least **7 distinct pairs** with some change, because the seeded split keeps 25 % for test and 20 % for validation "
        "and training needs at least 4. Your pairs flow through the same contract — validation, frozen baseline, adaptation, "
        "held-out evaluation, change maps, artifact export and reload parity — and Sections 5 and 6 start again from the "
        "pretrained model. The expected schema, the ceilings and the privacy guidance are stated in the Prerequisites and in "
        "Section 4, and uploaded files stay inside this runtime. BYOD is optional and never part of the default path."
    ),
    "pipeline_class": "CFNetChangePipeline",
    "model_load": "CFNetChangePipeline.from_pretrained(weights_dir=WEIGHTS_DIR, device=('cuda' if torch.cuda.is_available() else 'cpu'), report=print)",
    "weights_key": "cfnet-levir-cd",
    "modules": ["modeling.py", "metrics.py", "pipeline.py", "samples.py"],
    "entry_module": "pipeline.py",
    "runtime_imports": ["torch", "torchvision", "PIL"],
    "title": "CFNet bi-temporal change detection — DIMER E2E fine-tuning tutorial (standalone)",
    "badges": BADGES,
    "capability": "binary building-change maps for pairs of co-registered 0.5 m RGB patches with CFNet's content-focuser network, held-out F1/IoU against an all-unchanged baseline, and bounded fine-tuning of the change decoder to labelled pairs",
    "intro": (
        "CFNet (Wu et al., 2025) is a content-focuser network for bi-temporal remote-sensing change detection: a shared "
        "EfficientNet-B5 encoder over both dates, a content decoder per date trained to keep what is intrinsic to the scene "
        "rather than to its acquisition, a focuser that turns the cosine distance between the two dates' content maps into "
        "per-scale change weights, and a change decoder that fuses the dates with 3-D convolutions and decodes one change map. "
        "The checkpoint packaged here is the authors' LEVIR-CD model — trained on 0.5 m Google Earth patches of Texas cities "
        "taken 5–14 years apart with building-change labels (Chen and Shi, 2020) — which they report at F1 92.18 / IoU 85.49 "
        "on that dataset's test split.\n\n"
        "Three things about this row are handled in the open. **The upstream asset is a pickle** — a torch state dict saved "
        "with `torch.save`. Section 3 downloads and digest-verifies it, statically lists every global the pickle would import "
        "(a state dict of tensors and nothing else), refuses anything outside that allow-list, unpickles it exactly once "
        "through torch's weights-only loader, and writes a safetensors file whose digest is pinned in the carried module; the "
        "network you run is rebuilt from `modeling.py`, carried in this notebook, with the EfficientNet-B5 stages taken from "
        "the installed torchvision package (`weights=None`, no download) and loads that file strictly. **The dataset ships as "
        "one 3.8 GB tarball under academic-only terms**: LEVIR-CD may be used for academic purposes only, commercial use is "
        "prohibited, and the imagery is subject to Google Earth's terms — so Section 4 pins the authors' mirror of the tarball "
        "by size and digest, streams through it once and copies out exactly the 192 pinned members (each pinned again by size "
        "and digest, no `extractall`, no paths taken from the archive), leaves the other 47,589 alone, and redistributes "
        "nothing. **The model was trained on this dataset**, so the bounded adaptation in Section 6 is a demonstration of the "
        "contract on the training split's own crops, selected by validation loss with the frozen model as epoch 0 — and on "
        "this sample the honest outcome is that the frozen model is kept — while the test split, which the model never "
        "trained on, is the held-out set; the point of the contract is the same recipe applied to *your* labelled pairs.\n\n"
        "**Who this is for.** A learner who knows basic Python and NumPy, has met the idea of a neural network, and wants to "
        "see how a pretrained change detector is measured against a trivial baseline and adapted to labelled pairs without "
        "fooling themselves. No prior experience with remote sensing, change detection, CFNet or fine-tuning is assumed; each "
        "term is explained where it is first used and again in the **Glossary** at the end.\n\n"
        "**Input → Model → Output.**\n\n"
        "| | Detection | Adaptation |\n"
        "|---|---|---|\n"
        "| Input | two co-registered RGB images of one place (`before`, `after`), same size, sides 64..2,048 px and multiples of 32 | 32 training and 8 validation pairs, each with a 0 / 1 change label (−1 = ignore) |\n"
        "| Model | CFNet: shared EfficientNet-B5 encoder, two content decoders, focuser, change decoder | the same network; only the change decoder (852,867 parameters) is trained, BatchNorm statistics frozen |\n"
        "| Output | a change map in (−1, 1) and a binary mask (changed where the map exceeds 0.5) | the kept epoch (the frozen model competes as epoch 0), held-out F1 / IoU against the baseline and the frozen model, and a safetensors adapter that reloads with parity |\n\n"
        "**How to use this notebook.** Choose a runtime (a GPU runtime is faster; CPU works), then **Runtime → Run all**. "
        "Sections 1–3 are **infrastructure** — the isolated environment, the carried code (collapsed) and the model "
        "verification — and can be run without study. The learning path starts in Section 4. Form fields (`# @param`) are the "
        "only values meant to be edited; the defaults reproduce the recorded path. Each stage states what it does and asks you "
        "to **predict** before it runs; the next markdown cell opens with **What to notice** and a collapsible **Check your "
        "reasoning** block with a worked answer from a recorded run. Sections 5 and 6 always start from the pretrained model, "
        "so any re-run (BYOD or an experiment) compares against the untouched checkpoint. Section 9 is a **change-one-thing "
        "activity**; each optional experiment names the cell to change and the cell to re-run from (**Runtime → Run after**). "
        "**Troubleshooting**, a **Glossary** and a **Conclusion** template are at the end. Your notes are optional and are not "
        "required submissions.\n\n"
        "**Roadmap:** 4 extract, validate and split the pinned pairs → 5 the frozen model against the all-unchanged baseline → "
        "6 bounded fine-tuning of the change decoder, selected on a deterministic validation loss → 7 the paired held-out "
        "comparison → 8 change maps, export and reload → 9 **change one thing: the learning rate** → conclude."
    ),
    "learning_objectives": (
        "by the end you should be able to (1) explain *two dates → shared encoder, content decoders, focuser, change decoder "
        "→ change map → binary mask* and why the map is not a probability (Section 5); (2) read changed-class F1, IoU, "
        "precision and recall against the all-unchanged baseline and say why accuracy alone misleads (Section 5); (3) explain "
        "how the validation loss chooses the kept epoch, why the frozen model competes as epoch 0, and why a loss difference "
        "smaller than its draw-to-draw noise is not evidence of improvement (Section 6); (4) predict and then check whether "
        "adaptation changes the held-out numbers (Section 7); (5) explain why roles come from the dataset's splits and why real "
        "data must be split by scene, not by crop; (6) predict and then measure how a larger learning rate changes the kept "
        "epoch (Section 9); and (7) check that an exported adapter reproduces the evaluated model (reload parity, Section 8). "
        "Along the way the notebook stages, digest-verifies, audits and converts a pickled checkpoint, and extracts pinned "
        "members from a digest-verified tarball."
    ),
    "exclusions": (
        "multi-class or semantic change, change between more than two dates, images that are not co-registered, resolutions "
        "far from 0.5 m, tiling of scenes larger than a patch, the published benchmark scores, the CLCD and SYSU-CD checkpoints "
        "of the same repository, and any claim that a 64-crop sample stands in for an operational evaluation. The repository "
        "exposes none of these."
    ),
    "prerequisites": [
        "- **Learner:** basic Python and NumPy, and Colab or Jupyter familiarity; no prior experience with remote sensing, change detection or fine-tuning. The notebook explains co-registration, the change map and its threshold, F1 / IoU against a baseline, the content-consistency terms, epoch 0 and validation selection where they are first used; the Glossary repeats them.",
        "- **Runtime:** a fresh supported runtime (Google Colab, Kaggle or Linux Jupyter — **Linux x86_64 only**; the notebook builds its own isolated Python 3.12.12 environment, and a Windows or macOS kernel is not supported). The default path runs on CPU and uses CUDA automatically when available (float16 autocast on CUDA); a GPU runtime is recommended. Measured, each figure with its environment: on a Kaggle Tesla T4 (2026-09-20, an earlier version of this notebook) the tarball fetch and extraction took 69.4 s, the four-epoch adaptation 4.6 s and the whole second pass 105.1 s; in local CPU runs of this version (2026-10-03, a shared 24-thread Windows workstation, CPython 3.12, torch 2.14.0+cpu, files pre-staged, no install) the default path took 106–128 s, of which Section 6 took 70–72 s; with torch limited to 8 threads the four-epoch adaptation alone took 21.3 s. No hosted CPU run is recorded; on a 2-vCPU hosted CPU runtime expect the adaptation to take several times the workstation figure (an estimate). The locked install (PyTorch 2.14.0 with its CUDA libraries) and the 3.8 GB tarball are the large downloads; about 4 GB of free disk is needed for the tarball, and the checkpoint and its conversion are 31 MB together.",
        "- **Knowledge:** what a co-registered bi-temporal image pair is, what a binary change mask and an ignore class are, and how F1, IoU, precision and recall of a rare class are read against a majority baseline (all explained again where used).",
        "- **Executable serialization handled explicitly:** the pinned checkpoint is a pickle. It is digest-verified, statically audited against an allow-list (audit digest pinned) and unpickled **once** through torch's weights-only loader to produce the safetensors the network is actually loaded from. No Hub-hosted Python module is imported; the network is the carried `modeling.py` plus torchvision's EfficientNet-B5 stages built without weights.",
        "- **Data contract:** a record is `{id, before, after, label}` — two (H, W, 3) uint8 RGB images (or PNG / JPEG paths) of the same size, sides in [64, 2048] and multiples of 32, and an (H, W) mask with 0 / 1 / −1 (or a PNG with 0 / 255). A dataset holds 4..2,000 records. The pipeline reorders the channels to BGR and standardises each date with its own LEVIR-CD statistics, exactly as the upstream loader did. Validation is structural: nothing checks that the two images show the same place, that they are co-registered, that the resolution is about 0.5 m, or that the label belongs to the pair.",
        "- **BYOD contract:** a `.zip` (upload dialog on Colab, or `BYOD_PATH` on any runtime) or a directory holding one `pairs.csv` with columns `id`, `before`, `after`, `label` and the image files, paths relative to `pairs.csv` (a bare file name may also sit in a sub-folder when it is unique). The seeded split keeps 25 % of the distinct pairs for test (at least one) and 20 % for validation, and training needs at least 4, so a BYOD set needs at least **7 distinct pairs**; duplicates are removed first. Ceilings checked before any image is decoded: at most 6,001 files and 512 MB uncompressed in the zip. A missing or ambiguous file is refused with a message naming the row and the file.",
        "- **Privacy and terms:** Do not upload confidential or restricted data to a hosted runtime unless you are authorized to process it there — commercial imagery under licence is exactly that. The default path uploads nothing. LEVIR-CD, which the default path fetches, may be used **for academic purposes only**; commercial use is prohibited and the imagery is subject to Google Earth's terms of use.",
    ],
    "cells": [
        {
            "md": (
                "## 4. Sample pairs, validation and roles\n\n"
                "The default dataset is 64 labelled 256 × 256 crops of LEVIR-CD as the CFNet authors processed them (25 "
                "overlapping crops of every 1024 × 1024 pair): one crop from each of 32 training pairs, 8 validation pairs and "
                "24 test pairs, drawn with a fixed seed from the crops whose label is a clean 0 / 255 mask with at least 3 % "
                "change, so every crop can be scored. Roles are the dataset's own splits — the checkpoint was trained on the "
                "training split, selected on the validation split and reported on the test split. `fetch_corpus` downloads the "
                "tarball from the Hub at its immutable revision, refuses it on any size or SHA-256 mismatch, streams through it "
                "once and copies out exactly the 192 pinned members — each refused on its own size or digest mismatch and "
                "written under a flat name, never at a path taken from the archive — then reads the RGB PNGs and the masks, "
                "which become 0 / 1. `dataset_manifest` validates every split, checks that no crop and no source pair appears "
                "twice and records a digest. Allow a few minutes on the first run for the 3.8 GB tarball (69.4 s for fetch and "
                "extraction on a Kaggle T4, 2026-09-20); files already verified are reused.\n\n"
                "Three **refusal probes** each change one thing about one test pair — dates of different sizes, a side that is "
                "not a multiple of 32, a mask with an unknown value — and validate that pair on its own, so each refusal names "
                "the condition it probes, whatever the size of the test split.\n\n"
                "**Bring your own data (optional).** With `USE_BYOD = True` the cell reads your set from `BYOD_PATH` (a `.zip` "
                "or a directory) or, when that is empty, from the Colab upload dialog. Before any model runs it checks the "
                "archive's file count and uncompressed size, resolves every file named in `pairs.csv`, splits the distinct "
                "pairs (25 % test, 20 % validation, the rest training; at least **7 distinct pairs**) and validates every "
                "split, naming what it refuses. An empty or cancelled upload asks you to choose a file or set `BYOD_PATH`.\n\n"
                "**Predict before running:** the crops were chosen to have at least 3 % change. What change fraction do you "
                "expect per split — closer to 0.01, 0.1 or 0.5? And which of the three refusal probes do you expect the "
                "validator to accept?"
            ),
            "code": (
                "import json\n"
                "import os\n"
                "import time\n"
                "from pathlib import Path\n\n"
                "import numpy as np\n\n"
                "USE_BYOD = False  # @param {{type:\"boolean\"}}\n"
                "BYOD_PATH = ''  # @param {{type:\"string\"}}\n\n"
                "os.makedirs('outputs', exist_ok=True)\n"
                "t0 = time.perf_counter()\n"
                "if USE_BYOD:\n"
                "    if BYOD_PATH.strip():\n"
                "        byod_path = Path(BYOD_PATH.strip()).expanduser()\n"
                "        if not byod_path.exists():\n"
                "            raise FileNotFoundError(f'BYOD_PATH {{str(byod_path)!r}} does not exist; set it to a .zip or a directory holding pairs.csv')\n"
                "        file_name = byod_path.name\n"
                "    else:\n"
                "        from google.colab import files\n"
                "        uploaded = files.upload()\n"
                "        if len(uploaded) != 1:\n"
                "            raise ValueError(f'Upload exactly one .zip file (received {{len(uploaded)}}): run this cell again and choose the file, or set BYOD_PATH to a .zip or a directory.')\n"
                "        file_name, payload = next(iter(uploaded.items()))\n"
                "        byod_path = Path('work') / file_name\n"
                "        byod_path.parent.mkdir(parents=True, exist_ok=True)\n"
                "        byod_path.write_bytes(payload)\n"
                "    byod_records = load_byod_dataset(byod_path)\n"
                "    splits = split_dataset(byod_records, seed=0)\n"
                "    data_source = 'BYOD (' + file_name + ')'\n"
                "else:\n"
                "    splits = fetch_sample_dataset(cache_dir='weights/levir-cd')\n"
                "    data_source = SAMPLE_LABEL_SOURCE\n"
                "data_seconds = round(time.perf_counter() - t0, 1)\n"
                "train_records, val_records, test_records = splits['train'], splits['validation'], splits['test']\n\n"
                "dataset_report = dataset_manifest({{'train': train_records, 'validation': val_records, 'test': test_records}})\n"
                "print({{'data_source': data_source, 'splits': {{k: v['n_records'] for k, v in dataset_report['splits'].items()}}, 'disjoint': dataset_report['disjoint'], 'digest': dataset_report['digest'][:16] + '...', 'seconds': data_seconds}})\n"
                "for name, part in dataset_report['splits'].items():\n"
                "    print({{name: {{'change_fraction': part['change_fraction'], 'sizes': part['sizes'], 'ignored_pixels': part['ignored_pixels'], 'source_pairs': len(part['regions'])}}}})\n"
                "print({{'first_test_pair': validate_inputs(test_records[0])}})\n"
                "sample_pair = write_sample_pair(test_records[0], 'outputs/{stem}_sample_before.png', 'outputs/{stem}_sample_after.png', 'outputs/{stem}_sample_label.png')\n"
                "print({{'sample_pair': sample_pair, 'pairs_csv': str(write_dataset_csv(test_records, 'outputs/{stem}_sample_pairs.csv'))}})\n\n"
                "print({{'validation': INPUT_SCHEMA['validation'], 'byod_minimum_pairs': minimum_pairs(), 'byod_split': {{'test': BYOD_TEST_FRACTION, 'validation': BYOD_VAL_FRACTION}}}})\n"
                "probe = test_records[0]\n"
                "probes = {{\n"
                "    'dates of different sizes': {{**probe, 'after': probe['after'][:128, :128]}},\n"
                "    'side not a multiple of 32': {{**probe, 'before': probe['before'][:200, :200], 'after': probe['after'][:200, :200], 'label': probe['label'][:200, :200]}},\n"
                "    'unknown label value': {{**probe, 'label': np.where(probe['label'] == 1, 2, probe['label'])}},\n"
                "}}\n"
                "for name, record in probes.items():\n"
                "    try:\n"
                "        validate_dataset([record], min_records=1)\n"
                "        print({{'probe': name, 'verdict': 'accepted'}})\n"
                "    except (TypeError, ValueError) as exc:\n"
                "        print({{'probe': name, 'rejected': str(exc)[:110]}})"
            ),
        },
        {
            "md": (
                "**What to notice:** 32 / 8 / 24 crops from as many source pairs, change fractions near 0.1, and three "
                "refusals that each name the condition probed.\n\n"
                "<details><summary>Check your reasoning</summary>Closer to 0.1: in the local CPU run of this version "
                "(2026-10-03) the change fractions were 0.103 (training), 0.128 (validation) and 0.139 (test) — the 3 % floor "
                "only removes crops with almost no change, and building change is still a minority class. None of the probes "
                "is accepted: the different-sized dates are refused because before and after must have the same shape, the "
                "200-pixel side because sides must be multiples of 32, and the mask because the value 2 is outside {{0, 1, −1}} "
                "— each rejected by `validate_dataset` before the model runs.</details>\n\n"
                "## 5. The frozen model against the all-unchanged baseline\n\n"
                "`pipe.predict` reorders each image to BGR, divides by 255 and standardises each date with its own LEVIR-CD "
                "statistics — exactly the upstream loader's preprocessing — runs the shared encoder, the two content decoders, "
                "the focuser and the change decoder (in float16 autocast on a GPU), and returns the change map (the network's "
                "`tanh` output in (−1, 1), not a calibrated probability), the binary mask (changed where the map exceeds 0.5, "
                "the upstream rule) and the changed fraction per pair. `pipe.evaluate` pools the labelled pixels of every "
                "held-out pair into one confusion matrix (−1 pixels excluded) and reports the F1, IoU, precision and recall of "
                "the changed class exactly as the upstream evaluation does, plus the overall accuracy; the **all-unchanged "
                "baseline** — every pixel predicted unchanged — is scored on the same pixels, so its accuracy is exactly the "
                "unchanged fraction and its F1 and IoU are 0.\n\n"
                "**Every pass starts from the pretrained model.** The cell first calls `pipe.reset_to_pretrained()`, which "
                "re-verifies the converted file's digest and restores every tensor, so a re-run after an adaptation (BYOD, an "
                "experiment) scores the untouched checkpoint; it prints `adapted: False` and stops if that is not so.\n\n"
                "**Predict before running:** the all-unchanged baseline will score an accuracy of about 0.86 on the test crops. "
                "What F1 will it score, and would an accuracy of 0.90 from a model be good news?"
            ),
            "code": (
                "import time\n\n"
                "pipe.reset_to_pretrained()  # Sections 5 and 6 always start from the pretrained model\n"
                "t0 = time.perf_counter()\n"
                "frozen_test = pipe.evaluate(test_records)\n"
                "frozen_val = pipe.evaluate(val_records)\n"
                "if frozen_test['adapted'] or frozen_val['adapted']:\n"
                "    raise RuntimeError('Section 5 must score the pretrained model, but the pipeline is adapted: run this cell again (it resets the model first).')\n"
                "print({{'seconds': round(time.perf_counter() - t0, 1), 'adapted': frozen_test['adapted'], 'metric': frozen_test['metric']}})\n"
                "print({{'baseline_unchanged_test': {{k: frozen_test['baseline_unchanged'][k] for k in ('f1', 'iou', 'accuracy')}}}})\n"
                "print({{'frozen_test': {{k: frozen_test['model'][k] for k in ('f1', 'iou', 'precision', 'recall', 'accuracy', 'change_fraction_label', 'change_fraction_predicted')}}}})\n"
                "print({{'frozen_validation': {{k: frozen_val['model'][k] for k in ('f1', 'iou')}}}})\n"
                "frozen_predictions = pipe.predict(test_records)\n"
                "for record, pred in list(zip(test_records, frozen_predictions['predictions']))[:6]:\n"
                "    labelled = record['label'] >= 0\n"
                "    print({{'pair': record.get('source_id', record['id']), 'change_label': round(float((record['label'] == 1).sum() / labelled.sum()), 3), 'change_predicted': pred['changed_fraction'], 'map_range': [round(float(pred['change_map'].min()), 3), round(float(pred['change_map'].max()), 3)]}})\n"
                "print({{'decision_rule': frozen_predictions['decision_rule'], 'map_shape': frozen_predictions['predictions'][0]['change_map'].shape}})"
            ),
        },
        {
            "md": (
                "**What to notice:** the baseline's F1 and IoU of 0 beside its high accuracy, and the frozen model's F1 and "
                "IoU on the same pixels.\n\n"
                "<details><summary>Check your reasoning</summary>The baseline's F1 is 0: it never predicts the changed class, "
                "so it has no true positives. Its accuracy is the unchanged fraction, 0.8615 on these 24 crops, so a model at "
                "0.90 accuracy would barely beat doing nothing — read the changed-class numbers instead. The frozen model "
                "scored F1 0.9352 and IoU 0.8782 (precision 0.9424, recall 0.9281; validation F1 0.9152) in the local CPU run "
                "of this version (2026-10-03); the earlier Kaggle T4 build record printed the same F1 and IoU with precision "
                "0.9423 (float16 on the GPU). The authors report F1 92.18 / IoU 85.49 on the full test split, whose crops are "
                "mostly change-free; these are sample-sanity numbers on 24 crops chosen for having change, not the "
                "benchmark.</details>\n\n"
                "## 6. Bounded fine-tuning of the change decoder\n\n"
                "**Adaptation always starts from the pretrained model.** The cell calls `pipe.reset_to_pretrained()` first, and "
                "`pipe.adapt` refuses an already adapted pipeline, so epoch 0 is always the frozen checkpoint.\n\n"
                "`pipe.adapt` trains the 72 parameter tensors of the change decoder (852,867 parameters — 22 % of the model) and nothing "
                "else: the encoder and the two content decoders are frozen (no gradient is stored for them), and every "
                "BatchNorm layer keeps its running statistics, because batches of four crops would corrupt them. Each step "
                "takes four pairs with a seeded horizontal or vertical flip applied to both dates and the label, computes the "
                "upstream loss — the mean squared error between the `tanh` change map and the 0 / 1 target over the labelled "
                "pixels, plus 0.1 times the **content-consistency terms**, which compare cosine similarities of *randomly drawn "
                "pixel pairs* within each date's focused and unfocused content maps — and takes an AdamW step at a small fixed "
                "learning rate with gradient-norm clipping and float16 loss scaling.\n\n"
                "**How the kept epoch is chosen.** Epoch 0 records the frozen model's validation loss and metrics; after each "
                "epoch the validation loss is computed again, and the epoch with the lowest validation loss is kept — which can "
                "be epoch 0. Because the content terms draw random pixel pairs, the *same* weights score differently with "
                "different draws. The validation loss therefore re-seeds its draws identically for every epoch (`validation_loss`, "
                "draw seed 0), so epochs are compared on the same pixel pairs and the comparison reflects the weights, not the "
                "draw. Before training, the cell scores the frozen model with five different draw seeds: the spread of those "
                "five numbers is the size of the noise a single draw carries, and a difference between epochs smaller than "
                "that spread is not, on its own, evidence that anything improved. `TRAINABLE = 'decoders'` also unfreezes the "
                "two content decoders (1.75 M parameters).\n\n"
                "**Predict before running:** the model already trained on these 32 training crops. Will any of the four epochs "
                "beat the frozen model's validation loss, or will validation keep epoch 0?"
            ),
            "code": (
                "EPOCHS = 4  # @param {{type:\"integer\"}}\n"
                "LEARNING_RATE = 1e-5  # @param {{type:\"number\"}}\n"
                "BATCH_SIZE = 4  # @param {{type:\"integer\"}}\n"
                "TRAINABLE = 'change_decoder'  # @param [\"change_decoder\", \"decoders\"]\n\n"
                "pipe.reset_to_pretrained()  # epoch 0 must be the frozen model, whatever ran before\n"
                "draw_noise = [round(pipe.validation_loss(val_records, batch_size=BATCH_SIZE, draw_seed=s), 5) for s in range(5)]\n"
                "draw_noise_span = round(max(draw_noise) - min(draw_noise), 5)\n"
                "print({{'frozen_validation_loss_by_draw_seed': draw_noise, 'span': draw_noise_span, 'note': 'same weights, five different random pixel-pair draws'}})\n\n"
                "def report(entry):\n"
                "    row = {{'epoch': entry['epoch'], 'train_loss': None if entry['train_loss'] is None else round(entry['train_loss'], 5), 'val_loss': round(entry['val_loss'], 5)}}\n"
                "    if 'val' in entry:\n"
                "        row['val_f1'] = entry['val']['f1']\n"
                "        row['val_iou'] = entry['val']['iou']\n"
                "    if 'note' in entry:\n"
                "        row['note'] = entry['note']\n"
                "    print(row)\n\n"
                "t0 = time.perf_counter()\n"
                "adapt_result = pipe.adapt(train_records, val_records, epochs=EPOCHS, lr=LEARNING_RATE, batch_size=BATCH_SIZE, trainable=TRAINABLE, progress=report)\n"
                "adapt_seconds = round(time.perf_counter() - t0, 1)\n"
                "print({{'trainable_parameters': adapt_result['n_trainable'], 'total_parameters': adapt_result['n_total'], 'steps': adapt_result['n_steps'], 'best_epoch': adapt_result['best_epoch'], 'loss': adapt_result['loss'], 'precision': adapt_result['precision'], 'batchnorm': adapt_result['batchnorm'], 'seconds': adapt_seconds}})\n"
                "print({{'selection': adapt_result['selection']}})"
            ),
        },
        {
            "md": (
                "**What to notice:** the five-draw spread of the frozen model, the validation loss of each epoch beside it, "
                "and `best_epoch`.\n\n"
                "<details><summary>Check your reasoning</summary>Validation kept **epoch 0**, the frozen model. In the local "
                "CPU run of this version (2026-10-03) the frozen model's validation loss over five draw seeds ranged from "
                "0.11518 to 0.11621 (a span of about 0.001), and on the fixed draw the epochs scored 0.11621 (epoch 0) → "
                "0.11626 → 0.11637 → 0.11649 → 0.11658: every epoch was slightly worse than the frozen model, and validation F1 "
                "drifted from 0.9152 to 0.9121. A model that already trained on these crops has little left to learn from them "
                "at a small learning rate, and keeping epoch 0 is the honest answer. (An earlier version of this notebook let "
                "the draws advance from epoch to epoch and read a fall from 0.1162 to 0.1141 as selection working; that "
                "difference was smaller than the spread above, and on identical draws the epoch it kept was worse than the "
                "frozen model.)</details>\n\n"
                "## 7. Held-out evaluation: the paired comparison\n\n"
                "The test crops were never used for training or epoch selection — neither here nor by the upstream authors, "
                "whose model was trained on the training split and selected on the validation split. The adapted model (the "
                "kept epoch) is scored exactly as the frozen model was in Section 5, and the table puts the baseline, the frozen "
                "and the adapted numbers side by side. A **run summary** names what this run kept and what it changed; it is "
                "added to a **run history**, so a re-run (Section 9, an experiment, BYOD) adds a row you can compare. The cell "
                "checks what the procedure guarantees — the kept epoch's validation loss is no higher than the frozen model's, "
                "and re-scoring the validation crops reproduces the kept epoch's F1 within 0.01 (float16 kernels are not "
                "bit-reproducible across batch sizes) — and stops with a message naming the cause if either fails. It prints "
                "the test numbers without asserting a direction: 24 crops with no dispersion estimate give a sample-sanity "
                "observation, not a quality claim. With your own pairs from another city, sensor or season, the gap between "
                "frozen and adapted is the number to watch.\n\n"
                "**Predict before running:** if validation kept epoch 0, what will the adapted test F1 be compared with the "
                "frozen test F1?"
            ),
            "code": (
                "adapted_test = pipe.evaluate(test_records)\n"
                "adapted_val = pipe.evaluate(val_records)\n"
                "comparison = {{}}\n"
                "for key in ('f1', 'iou', 'precision', 'recall', 'accuracy'):\n"
                "    comparison[key] = {{'baseline_unchanged': frozen_test['baseline_unchanged'][key], 'frozen': frozen_test['model'][key], 'adapted': adapted_test['model'][key]}}\n"
                "for key, row in comparison.items():\n"
                "    print({{key: row}})\n"
                "history = adapt_result['history']\n"
                "kept = history[adapt_result['best_epoch']]\n"
                "selection = {{'kept_epoch': adapt_result['best_epoch'], 'validation_loss': {{'frozen': round(history[0]['val_loss'], 5), 'kept_epoch': round(kept['val_loss'], 5)}}, 'margin': round(history[0]['val_loss'] - kept['val_loss'], 5), 'frozen_draw_noise_span': draw_noise_span, 'rule': adapt_result['selection']}}\n"
                "print({{'validation_f1': {{'frozen': frozen_val['model']['f1'], 'adapted': adapted_val['model']['f1']}}, 'selection': {{k: v for k, v in selection.items() if k != 'rule'}}}})\n"
                "run_summary = {{\n"
                "    'data': ('BYOD ' + file_name) if USE_BYOD else 'LEVIR-CD sample',\n"
                "    'trainable': TRAINABLE,\n"
                "    'learning_rate': LEARNING_RATE,\n"
                "    'epochs': EPOCHS,\n"
                "    'kept_epoch': adapt_result['best_epoch'],\n"
                "    'kept': 'the frozen model (epoch 0)' if adapt_result['best_epoch'] == 0 else 'epoch ' + str(adapt_result['best_epoch']),\n"
                "    'test_f1': {{'frozen': frozen_test['model']['f1'], 'adapted': adapted_test['model']['f1']}},\n"
                "    'delta_f1': round(adapted_test['model']['f1'] - frozen_test['model']['f1'], 4),\n"
                "    'delta_iou': round(adapted_test['model']['iou'] - frozen_test['model']['iou'], 4),\n"
                "}}\n"
                "run_history = globals().get('run_history', [])\n"
                "run_history.append(run_summary)\n"
                "print({{'run_summary': run_summary}})\n"
                "print({{'run_history': [{{k: r[k] for k in ('trainable', 'learning_rate', 'epochs', 'kept_epoch', 'delta_f1')}} for r in run_history]}})\n"
                "evaluation_report = {{\n"
                "    'model': {{'id': MODEL_ID, 'revision': MODEL_REVISION, 'key': MODEL_KEY}},\n"
                "    'data_source': data_source,\n"
                "    'dataset': dataset_report,\n"
                "    'frozen': {{'test': frozen_test, 'validation': frozen_val}},\n"
                "    'adapted': {{'test': adapted_test, 'validation': adapted_val}},\n"
                "    'comparison': comparison,\n"
                "    'selection': selection,\n"
                "    'adaptation': {{k: v for k, v in adapt_result.items() if k not in ('history', 'trainable_names')}},\n"
                "    'history': history,\n"
                "    'adaptation_seconds': adapt_seconds,\n"
                "    'run_summary': run_summary,\n"
                "    'run_history': run_history,\n"
                "}}\n"
                "with open('outputs/{stem}_evaluation_report.json', 'w', encoding='utf-8') as f:\n"
                "    json.dump(evaluation_report, f, indent=2)\n"
                "if kept['val_loss'] > history[0]['val_loss']:\n"
                "    raise RuntimeError(f'The kept epoch scores worse than the frozen model on the selection criterion ({{selection}}); the selection rule was not applied. Run Section 6 again.')\n"
                "if abs(adapted_val['model']['f1'] - kept['val']['f1']) >= 1e-2:\n"
                "    raise RuntimeError(f\"Re-scoring the validation crops gave F1 {{adapted_val['model']['f1']}}, the kept epoch recorded {{kept['val']['f1']}}: the model in memory is not the kept epoch. Run Section 6 again.\")\n"
                "print({{'report': 'outputs/{stem}_evaluation_report.json'}})"
            ),
        },
        {
            "md": (
                "**What to notice:** the three-way table, the run summary (kept epoch, ΔF1, ΔIoU) and the selection margin "
                "beside the five-draw noise span.\n\n"
                "<details><summary>Check your reasoning</summary>Identical. When epoch 0 is kept, the adapted model *is* the "
                "frozen model, so every test number is the same: in the local CPU run of this version (2026-10-03) the "
                "changed-class F1 stayed 0.9352 and the IoU 0.8782 (ΔF1 0, ΔIoU 0), against an all-unchanged accuracy of 0.8615, "
                "and the selection margin was 0. The earlier build record, which kept a noise-selected epoch 2, moved the IoU by "
                "0.0001 — also nothing. On a model that trained on this dataset, \"do not adapt\" is the expected "
                "outcome.</details>\n\n"
                "## 8. Change maps, artifact export and fresh reload\n\n"
                "The adapted model's change maps of two held-out pairs are written as PNGs beside the two dates and the "
                "reference mask — the binary mask (0 / 255, the BYOD label convention) and the raw `tanh` map rescaled to "
                "0–255 — so they can be opened side by side: the agreement per pair printed here is a sanity check, not an "
                "evaluation.\n\n"
                "`pipe.save_artifact` writes the trained tensors of the kept epoch (about 3.4 MB; when epoch 0 was kept they are "
                "the frozen model's own change-decoder tensors) as `adapter.safetensors`, with a `manifest.json` recording the "
                "artifact format, the base model id and revision, the digest of the converted base file, the adaptation scope, "
                "the selection rule, the tensor names, the file size and SHA-256, the training configuration and the epoch "
                "history (OUT8). `CFNetChangePipeline.from_artifact` re-verifies the base file, checks the artifact manifest, "
                "scope and digest **before** deserialising, rebuilds the network and overlays the tensors — a fresh object from "
                "files, not the in-memory model (VER2). The cell removes any `result.json` of an earlier run first, checks the "
                "same held-out F1 within 0.001 and change maps within 0.01 (VER4: float16 tolerances; on one device they are "
                "usually identical), stops with a message naming the cause if they differ, and ends by printing the run "
                "summary, so the last output states what *your* run kept and what it changed.\n\n"
                "**Predict before running:** if validation kept epoch 0, will the change maps of the adapted and the reloaded "
                "model differ from the frozen model's?"
            ),
            "code": (
                "import platform\n"
                "import shutil\n\n"
                "from PIL import Image\n\n"
                "Path('outputs/{stem}_result.json').unlink(missing_ok=True)  # never leave an earlier run's result behind\n"
                "shown_records = test_records[:2]\n"
                "shown_predictions = pipe.predict(shown_records)\n"
                "for record, pred in zip(shown_records, shown_predictions['predictions']):\n"
                "    tag = record.get('source_id', record['id'])\n"
                "    Image.fromarray(record['before']).save(f'outputs/{stem}_before_' + tag + '.png')\n"
                "    Image.fromarray(record['after']).save(f'outputs/{stem}_after_' + tag + '.png')\n"
                "    Image.fromarray(np.where(record['label'] == 1, 255, 0).astype(np.uint8)).save(f'outputs/{stem}_label_' + tag + '.png')\n"
                "    Image.fromarray((pred['mask'] * 255).astype(np.uint8)).save(f'outputs/{stem}_change_adapted_' + tag + '.png')\n"
                "    Image.fromarray(np.clip((pred['change_map'] + 1.0) * 127.5 + 0.5, 0, 255).astype(np.uint8)).save(f'outputs/{stem}_map_adapted_' + tag + '.png')\n"
                "    labelled = record['label'] >= 0\n"
                "    print({{'pair': tag, 'agreement': round(float((pred['mask'] == record['label'])[labelled].mean()), 3), 'change_label': round(float((record['label'] == 1).sum() / labelled.sum()), 3), 'change_predicted': pred['changed_fraction'], 'note': 'sanity check on two pairs'}})\n"
                "with open('outputs/{stem}_predictions.json', 'w', encoding='utf-8') as f:\n"
                "    json.dump({{'model': shown_predictions['model'], 'classes': shown_predictions['classes'], 'decision_rule': shown_predictions['decision_rule'], 'predictions': [{{'id': p['id'], 'changed_fraction': p['changed_fraction']}} for p in shown_predictions['predictions']]}}, f, indent=2)\n\n"
                "artifact_dir = Path('outputs/{stem}_adapter')\n"
                "shutil.rmtree(artifact_dir, ignore_errors=True)\n"
                "pipe.save_artifact(artifact_dir, metadata={{'tutorial': '{stem}', 'data_source': data_source}})\n"
                "artifact_manifest = json.loads((artifact_dir / 'manifest.json').read_text(encoding='utf-8'))\n"
                "print({{'artifact': str(artifact_dir), 'format': artifact_manifest['format'], 'trainable': artifact_manifest['adapter']['trainable'], 'kept_epoch': artifact_manifest['adapter']['best_epoch'], 'tensors': len(artifact_manifest['tensors']), 'bytes': artifact_manifest['files'][0]['bytes'], 'sha256': artifact_manifest['files'][0]['sha256'][:16] + '...'}})\n\n"
                "reloaded = CFNetChangePipeline.from_artifact(artifact_dir, weights_dir=WEIGHTS_DIR, device=pipe.device)\n"
                "reloaded_test = reloaded.evaluate(test_records)\n"
                "before = pipe.predict(test_records[:2])['predictions']\n"
                "after = reloaded.predict(test_records[:2])['predictions']\n"
                "parity = {{'f1_diff': round(abs(reloaded_test['model']['f1'] - adapted_test['model']['f1']), 6), 'metrics_identical': reloaded_test['model'] == adapted_test['model'], 'max_abs_map_diff': max(float(np.abs(a['change_map'] - b['change_map']).max()) for a, b in zip(before, after))}}\n"
                "print({{'reload_parity': parity, 'reloaded_best_epoch': reloaded.adapter['best_epoch']}})\n"
                "if not (parity['f1_diff'] < 1e-3 and parity['max_abs_map_diff'] < 1e-2):\n"
                "    raise RuntimeError(f'Reload parity failed: {{parity}}. The saved adapter does not reproduce the evaluated model; run Section 6 again (it starts from the pretrained model), or restart the session and choose Run all.')\n\n"
                "result_payload = {{\n"
                "    'notebook_source': NOTEBOOK_SOURCE,\n"
                "    'repository_revision': NOTEBOOK_SOURCE['repository_revision'],\n"
                "    'model': {{**evaluation_report['model'], 'model_license': MODEL_LICENSE, 'device': pipe.device, 'source': pipe.source}},\n"
                "    'provenance': {{\n"
                "        'source_asset': [e for e in MANIFEST['files'] if e['path'] == SOURCE_CKPT_NAME],\n"
                "        'pickle_audit_sha256': PICKLE_AUDIT_SHA256,\n"
                "        'converted': verify_converted(WEIGHTS_DIR)['files'],\n"
                "        'pickle_unpickled_once_for_conversion': True,\n"
                "        'served_from_pickle': False,\n"
                "        'remote_code_executed': False,\n"
                "        'network_source': 'modeling.py carried in this notebook; EfficientNet-B5 stages from torchvision ' + torchvision.__version__ + ' with weights=None',\n"
                "        'data_tarball': {{'name': TAR_NAME, 'sha256': TAR_SHA256, 'pinned_members': 3 * len(SAMPLE_RECORDS)}},\n"
                "        'data_base_url': CORPUS_BASE_URL,\n"
                "        'data_license': CORPUS_LICENSE,\n"
                "    }},\n"
                "    'runtime': {{'python': platform.python_version(), 'torch': torch.__version__, 'torchvision': torchvision.__version__, 'pillow': PIL.__version__, 'numpy': np.__version__}},\n"
                "    'data_source': data_source,\n"
                "    'comparison': comparison,\n"
                "    'selection': selection,\n"
                "    'run_summary': run_summary,\n"
                "    'run_history': run_history,\n"
                "    'artifact': {{'dir': str(artifact_dir), 'sha256': artifact_manifest['files'][0]['sha256'], 'bytes': artifact_manifest['files'][0]['bytes'], 'kept_epoch': artifact_manifest['adapter']['best_epoch']}},\n"
                "    'reload_parity': parity,\n"
                "}}\n"
                "with open('outputs/{stem}_result.json', 'w', encoding='utf-8') as f:\n"
                "    json.dump(result_payload, f, indent=2)\n\n"
                "print('outputs/:')\n"
                "for path in sorted(Path('outputs').rglob('*')):\n"
                "    if path.is_file():\n"
                "        print(f'  - {{path.as_posix()}} ({{path.stat().st_size / 1024:.1f}} KB)')\n"
                "print({{'run_summary': run_summary}})"
            ),
        },
    ],
    "closing": (
        "**What to notice:** the agreement per pair, the adapter's kept epoch and tensor count, the reload-parity line, and "
        "the run summary printed last.\n\n"
        "<details><summary>Check your reasoning</summary>No. With epoch 0 kept, the adapter holds the frozen model's own "
        "72 change-decoder tensors (3,419,684 bytes), so the adapted, the reloaded and the frozen model are the same network "
        "and their maps are identical: in the local CPU run of this version (2026-10-03) the reload parity was f1_diff 0.0, "
        "metrics identical, maximum map difference 0.0. Exporting the frozen model is still a valid adapter — the contract "
        "lets the checkpoint win.</details>\n\n"
        "## 9. Your turn — change one thing: the learning rate\n\n"
        "Optional; **Predict → Change → Run → Observe → Explain**. It re-runs Sections 6–8, which takes about as long as "
        "they took the first time.\n\n"
        "1. **Predict:** with `LEARNING_RATE = 1e-3` (a hundred times the default), will validation still keep epoch 0, or "
        "will a trained epoch win? If one wins, will it also help on the held-out test crops? Write your guess next to the "
        "default run's row in the Section 7 run history.\n"
        "2. **Change:** in Section 6 set `LEARNING_RATE = 1e-3`. Change nothing else.\n"
        "3. **Run:** select the Section 6 cell and choose **Runtime → Run after**. Section 6 resets the model to the "
        "pretrained checkpoint before adapting, Section 7 compares against the same Section 5 frozen scores and adds a row to "
        "the run history, and Section 8 exports and reloads the new adapter.\n"
        "4. **Observe:** in Section 6, epoch 0 shows the frozen model's validation loss again (0.11621 in the local CPU run, "
        "not a value left over from the earlier run) and then the trained epochs; in Section 7, the run history now has two "
        "rows — compare `kept_epoch` and `delta_f1`; in Section 8, the adapter's kept epoch.\n"
        "5. **Explain:** in one sentence, why can a trained epoch win on validation loss and still lose on test F1?\n\n"
        "<details><summary>Check your reasoning</summary>Validation still keeps epoch 0. In the local CPU run of this version (2026-10-03) the epochs scored 0.11621 (epoch 0) → 0.11690 → 0.11828 → 0.12181 → 0.11955 and validation F1 fell from 0.9152 to 0.8888 at epoch 3, while the training loss kept falling (0.1110 → 0.1085): a step a hundred times larger pulls the change decoder away from weights already fitted to this data and over-fits 32 crops. So the frozen model was kept and the test F1 stayed 0.9352 (ΔF1 0). A trained epoch *can* win on validation and still lose on test because the validation loss is an estimate from 8 crops: a small win there can be luck of those 8 crops (and, with random pixel-pair draws, luck of the draw — which is why the draws are now fixed). If your epoch 0 did not show 0.11621 on a CPU (or within about 0.0001 of it on a GPU), the model was not reset: restart the session and choose **Run all**.</details>\n\n"
        "## Interpretation and limits\n\n"
        "Start from your own run summary (the last line of Section 8): which epoch did validation keep, and did the adapted "
        "model change the held-out F1 and IoU against the frozen model? Then read the baseline row before you believe any "
        "model number.\n\n"
        "<details><summary>Reference answer from the recorded runs</summary>On 24 held-out crops the packaged change detector "
        "finds building change with an F1 of 0.9352 and an IoU of 0.8782 against an all-unchanged baseline that scores 0 on "
        "both (accuracy 0.8615). At the default settings the bounded fine-tuning of the change decoder on 32 training crops "
        "made the validation loss slightly worse at every epoch, so validation kept the frozen model (epoch 0) and the test "
        "numbers did not move (local CPU run of this version, 2026-10-03). On BYOD data or with other settings your numbers "
        "describe a different run; read them, not these.</details>\n\n"
        "That is the claim: the adaptation contract runs end to end on real labelled bi-temporal pairs drawn from a "
        "digest-verified tarball, the pickle is audited and converted rather than served, the network is carried in plain "
        "PyTorch, the selection rule is deterministic and lets the checkpoint win, and the artifact that carries the result is "
        "3.4 MB and reloads with the same outputs. It is not a claim that this sample improves the model — the model already "
        "trained on this dataset — nor that 24 crops measure its skill.\n\n"
        "The numbers are sample-sanity evidence: one seeded run, 24 crops chosen for having change (the full test split is "
        "mostly change-free, which is why the authors' F1 is lower), no dispersion estimate, pixel-pooled metrics that let "
        "large buildings dominate, and labels drawn by hand with their own uncertainty at building edges. The validation loss "
        "that selects the epoch is itself an estimate from 8 crops and one fixed draw of pixel pairs; Section 6 shows how much "
        "the draw alone moves it. Nothing here measures the model outside Texas suburbs, outside 0.5 m Google Earth imagery, on "
        "pairs that are not co-registered, or on change that is not a building.\n\n"
        "Three things to carry to real data. **The two dates are not interchangeable:** the network standardises each date "
        "with its own statistics and its content decoders are separate, so `before` and `after` must be the earlier and the "
        "later image; a swapped or uncalibrated pair is compared without complaint and silently wrong. **Split by scene, not "
        "by crop:** overlapping crops of one scene are near-duplicates, and a random split makes memorisation look like "
        "skill. **Read the baseline first:** on a crop with 5 % change the all-unchanged baseline is 95 % accurate; only the "
        "changed-class F1, IoU, precision and recall say whether the detector did anything.\n\n"
        "Successful execution proves that the recorded repository revision's pipeline modules, carried in this standalone "
        "notebook, can acquire and digest-verify a pickled upstream checkpoint, audit and convert it into safetensors without "
        "executing anything outside the audited allow-list, rebuild the network from the carried module, fetch a digest-pinned "
        "tarball and extract exactly the pinned labelled pairs, execute bounded fine-tuning with deterministic validation "
        "selection, evaluate against a baseline and the frozen model on held-out pairs, and emit the shown machine-readable "
        "artifacts — without the repository being reachable. It does **not** establish benchmark superiority, production "
        "fitness, or change-detection skill beyond the checks shown.\n\n"
        "**Optional experiments (they do not affect the default path).** Each one changes one form field; note the numbers "
        "you want to compare first (the Section 7 run history keeps one row per pass). In Colab, **Runtime → Run after** runs "
        "the selected cell and every cell below it; Sections 5 and 6 reset the model to the pretrained checkpoint before they "
        "use it, so no experiment inherits an earlier adaptation. Decide what you expect before each run, then compare with "
        "the reference answer.\n\n"
        "- **Unfreeze the content decoders:** set `TRAINABLE = 'decoders'` in Section 6, select Section 6 and choose **Run "
        "after**. Does training 1.75 M parameters instead of 0.85 M change the kept epoch? <details><summary>Reference "
        "answer</summary>No: epoch 0 is kept again. In the local CPU run of this version (2026-10-03) the validation loss went 0.11621 → 0.11624 → 0.11634 → 0.11646 → 0.11655 and validation F1 0.9152 → 0.9121; twice the trainable parameters took about 1.6 times as long and found nothing the frozen model lacked on these crops.</details>\n"
        "- **Train longer:** set `EPOCHS = 8` in Section 6 and **Run after** from there. Does the validation loss ever fall "
        "below epoch 0? <details><summary>Reference answer</summary>No: in the local CPU run of this version (2026-10-03) the validation loss rose at every epoch, from 0.11621 at epoch 0 to 0.11683 at epoch 8, with validation F1 0.9152 → 0.9096; epoch 0 was kept and the test numbers did not move.</details>\n"
        "- **See the draw noise:** in Section 6 the frozen model is scored with five draw seeds before training. Compare that "
        "span with the gap between epoch 0 and the best trained epoch in your run: is the gap larger?\n"
        "- **Your own labelled pairs:** BYOD (Section 4, then **Run after**); read the baseline and the frozen row before the "
        "adapted number.\n\n"
        "## Troubleshooting\n\n"
        "- **Section 1 stops with \"needs a Linux x86_64 runtime\".** The locked environment is built from manylinux "
        "wheels. Use Google Colab, Kaggle or a Linux Jupyter server; Windows and macOS kernels are not supported.\n"
        "- **Section 1 fails while downloading** (`uv` wheel, Python build or packages). The runtime needs PyPI and the "
        "python-build-standalone download; run the cell again once the network is back. A \"size/SHA-256\" or \"does not "
        "match its digest\" error means a file was altered: do not edit the cell, regenerate the notebook from the "
        "repository.\n"
        "- **A restart prompt.** This notebook never needs a runtime restart: nothing is installed into the kernel. If the "
        "runtime restarted anyway (you chose it, or it was reset), choose **Run all** again from the top; files already "
        "downloaded and verified are reused while they are still there.\n"
        "- **\"The isolated environment's Python process exited\".** Usually the runtime ran out of memory. Restart the "
        "session and choose **Run all**; on CPU, close other notebooks first.\n"
        "- **Section 3 or 4 stops on a download** (the Hub snapshot or the tarball). The Hub was unreachable or the transfer "
        "was cut; run the cell again later. Files already verified are kept under `weights/` and are not fetched twice.\n"
        "- **A digest or size mismatch in Section 3 or 4.** A download was incomplete or altered; the notebook refuses it "
        "rather than continuing. Run the cell again; never edit the manifest or the pinned digests.\n"
        "- **Out of disk.** The tarball needs about 4 GB of free disk, the locked install a few GB more. Start a fresh "
        "runtime, or delete `dimer_isolated_env/` and `weights/levir-cd/` from an earlier attempt.\n"
        "- **BYOD is refused in Section 4.** The message names what to fix: fewer than 7 distinct pairs, a zip with more "
        "than 6,001 files or more than 512 MB uncompressed, a missing `pairs.csv` or column, a file named in `pairs.csv` "
        "that is not in the zip (or matches several files), dates of different sizes, a side outside 64..2,048 or not a "
        "multiple of 32, or a label value other than 0 / 255. Fix the set and run Section 4 with **Run after** again. An "
        "empty or cancelled upload asks you to choose one file or set `BYOD_PATH`.\n"
        "- **Section 7 or 8 stops with a message about the kept epoch or reload parity.** The model in memory is not the "
        "one the history or the artifact describes — usually a cell was re-run out of order. Run Section 6 with **Run after** "
        "(it starts from the pretrained model), or restart the session and choose **Run all**.\n"
        "- **Numbers differ slightly from the recorded runs.** GPU float16 arithmetic is not bit-for-bit the CPU's: a "
        "difference of 0.0001 in a precision or a validation loss between a T4 and a CPU run is expected, and on a GPU a "
        "trained epoch whose validation loss is within that difference of epoch 0 can be kept instead. Larger differences on "
        "the default settings mean a form field was changed.\n\n"
        "## Glossary\n\n"
        "- **Bi-temporal pair:** two images of the same place taken at two dates, `before` and `after`.\n"
        "- **Co-registered:** aligned so the same pixel shows the same ground position in both images.\n"
        "- **Change map:** the network's `tanh` output in (−1, 1) per pixel; not a calibrated probability.\n"
        "- **Binary mask / threshold:** changed where the change map exceeds 0.5 (the upstream rule).\n"
        "- **Ignore class:** label value −1, pixels excluded from every metric.\n"
        "- **All-unchanged baseline:** predicting \"unchanged\" everywhere; its accuracy is the unchanged fraction and its F1 "
        "and IoU are 0.\n"
        "- **F1 / IoU / precision / recall:** changed-class scores over the pooled labelled pixels; F1 is the harmonic mean "
        "of precision and recall, IoU the overlap of predicted and labelled change divided by their union.\n"
        "- **Content decoder / focuser / change decoder:** the per-date decoders that keep scene content, the module that "
        "turns their disagreement into change weights, and the decoder that outputs the change map (the only part trained by "
        "default).\n"
        "- **Content-consistency terms:** the part of the upstream loss that compares cosine similarities of randomly drawn "
        "pixel pairs within each date; the source of the draw noise.\n"
        "- **Epoch / epoch 0:** one pass over the training pairs; epoch 0 is the frozen checkpoint, scored before any "
        "training so it can win.\n"
        "- **Validation loss / draw seed:** the selection criterion, computed on the validation pairs with the content-term "
        "pixel pairs drawn from a fixed seed so every epoch is scored on the same draw.\n"
        "- **Training / validation / test split:** pairs used to train, to choose the epoch, and to report the final result "
        "once; here the dataset's own splits.\n"
        "- **Adapter / reload parity:** the saved tensors of the kept epoch, and the check that a pipeline rebuilt from them "
        "gives the same change maps and metrics.\n\n"
        "## Conclusion (your notes)\n\n"
        "Optional personal notes, not a required submission. Complete each sentence from your own run:\n\n"
        "- On these test pairs the all-unchanged baseline scored accuracy ___ and F1 ___; the frozen model scored F1 ___ and "
        "IoU ___.\n"
        "- Validation kept epoch ___; the margin over epoch 0 was ___ against a draw-noise span of ___, so ___.\n"
        "- With `LEARNING_RATE = ___` (Section 9) validation kept epoch ___ and the held-out F1 moved by ___, because ___.\n"
        "- Before trusting an adapted change detector on my own imagery I would measure ___ on ___.\n\n"
        "## References\n\n"
        "- Repository README: https://github.com/kurtvalcorza/cfnet-change-detection-pipeline/blob/main/README.md\n"
        "- Repository model card: https://github.com/kurtvalcorza/cfnet-change-detection-pipeline/blob/main/MODEL_CARD.md\n"
        "- Weights and conversion notes: https://github.com/kurtvalcorza/cfnet-change-detection-pipeline/blob/main/docs/WEIGHTS.md\n"
        "- Hugging Face model repository: https://huggingface.co/wifibk/CFNet (revision `{MODEL_REVISION}`)\n"
        "- LEVIR-CD dataset (academic use only): https://justchenhao.github.io/LEVIR/ · the CFNet authors' mirror: https://huggingface.co/datasets/wifibk/CFNet_Datasets\n"
        "- Wu, F., Dong, S., Meng, X. (2025). CFNet: Optimizing remote sensing change detection through content-aware enhancement. arXiv:2503.08505: https://arxiv.org/abs/2503.08505\n"
        "- Chen, H., Shi, Z. (2020). A spatial-temporal attention-based method and a new dataset for remote sensing image change detection. Remote Sensing 12(10), 1662 (LEVIR-CD)\n"
        "- Upstream code: https://github.com/wifiBlack/CFNet (the network is vendored in `modeling.py`)\n"
        "- DIMER Notebook Specification 2.2 and Model Card Specification 1.1 (fleet specs in the ml-worker repository)\n"
    ),
}
